-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 11, 2025 at 04:01 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `electrogadgets`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE `cart` (
  `cart_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `quantity` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `category_id` int(11) NOT NULL,
  `category_name` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`category_id`, `category_name`) VALUES
(1, 'Apple Watch'),
(2, 'Console'),
(3, 'Earbuds'),
(4, 'iPad'),
(5, 'iPhones'),
(6, 'Mac'),
(7, 'Projector'),
(8, 'Smart TV');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `order_quantity` int(11) NOT NULL,
  `total_price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `product_id` int(11) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `stocks` int(11) NOT NULL,
  `image_path` varchar(100) NOT NULL,
  `price` int(11) NOT NULL,
  `category_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_name`, `description`, `stocks`, `image_path`, `price`, `category_id`) VALUES
(1, 'AirPods Pro 2', 'The AirPods Pro 2 deliver an unrivaled wireless audio experience with personalized Spatial Audio and next-level Active Noise Cancellation. Enhanced by the H2 chip for exceptional sound quality, these earbuds feature adaptive transparency mode that reduces harsh environmental noise, a redesigned touch control system, and up to 6 hours of listening time on a single charge. The charging case now includes a built-in speaker for Find My alerts and a lanyard loop for added convenience. IPX4 sweat and water resistance makes them perfect for workouts and daily use. The improved drivers and amplifiers produce richer bass and crystal-clear high frequencies, while the redesigned microphones ensure superior call quality even in windy conditions. The case provides an additional 30 hours of battery life and supports both MagSafe and Qi wireless charging for ultimate convenience.', 28, 'assets/img/airpods2pro.webp', 17000, 3),
(2, 'Apple Watch Hermès', 'The Apple Watch Hermès represents the ultimate fusion of technology and luxury fashion. Featuring exclusive Hermès leather bands handcrafted by skilled artisans using traditional techniques, distinctive watch faces inspired by iconic Hermès timepieces, and premium craftsmanship throughout. This special edition combines the advanced health monitoring, fitness tracking, and connectivity features of Apple Watch with the timeless elegance and heritage of the Hermès fashion house. Each watch comes in special packaging with an extra Sport Band and features an etched Hermès signature on the back crystal. The stainless steel case is polished to perfection and paired with bands made from the finest quality leather, including options in Single Tour, Double Tour, and the distinctive Hermès deployment buckle designs. The exclusive Hermès watch faces feature the iconic orange accent color and typography that perfectly complement the bands. Advanced health features include ECG, blood oxygen monitoring, and temperature sensing, all while maintaining the distinctive luxury aesthetic that has defined Hermès for generations.', 10, 'assets/img/appleWatchHermes.webp', 76000, 1),
(3, 'Apple Watch Nike Series', 'The Apple Watch Nike Series combines style and performance for fitness enthusiasts. Featuring exclusive Nike watch faces designed to complement the Nike Run Club experience, specialized workout features including pace alerts and cadence tracking, and the Nike Run Club integration for guided runs with audio coaching. The breathable Nike Sport Band or Sport Loop is designed for optimal comfort during intense workouts, while the reflective yarn improves visibility during night runs. Enjoy all standard Apple Watch features plus exclusive Nike training content, challenges, and rewards to keep you motivated. The aluminum case is lightweight yet durable, perfect for active lifestyles, while the Ion-X strengthened glass protects against scratches and impacts during workouts. Advanced metrics track your running form, ground contact time, and vertical oscillation to help improve your technique. The always-on altimeter provides real-time elevation data for hikers and trail runners, while the built-in compass ensures you stay on course. Water resistance to 50 meters makes it suitable for swimming workouts, with dedicated tracking for pool and open water sessions.', 25, 'assets/img/appleWatchNike.webp', 23000, 1),
(4, 'Apple Watch SE 2nd Gen', 'The Apple Watch SE 2nd Generation brings essential Apple Watch features at a great value. Perfect for fitness tracking with comprehensive workout metrics, staying connected with calls and messages, and monitoring your health with heart rate notifications and sleep tracking. Powered by the S8 SiP advanced processor, it delivers fast performance and efficient battery life. The watch includes Crash Detection, Fall Detection, and Emergency SOS for peace of mind. Available in lightweight aluminum cases with a variety of band options, it\'s the perfect entry point into the Apple Watch ecosystem without compromising on core functionality. The Retina display is bright and responsive, with thin borders that maximize the viewing area. Track dozens of workout types with accurate calorie calculations and trend analysis to monitor your progress over time. The watch automatically detects when you start a workout and reminds you to stop tracking when you\'re finished. Family Setup allows you to set up watches for family members who don\'t have iPhones, making it perfect for children and older adults. With regular software updates, your Apple Watch SE continues to gain new features and capabilities over time.', 30, 'assets/img/appleWatchSE2nd.webp', 16000, 1),
(5, 'Apple Watch Series 10', 'The Apple Watch Series 10 represents the pinnacle of smartwatch technology. With advanced health monitoring including ECG, blood oxygen level measurement, and temperature sensing, this device provides comprehensive insights into your wellbeing. The stunning always-on Retina display features ultra-thin borders and exceptional brightness even in direct sunlight. Powered by the latest S10 chip, it delivers powerful performance capabilities while maintaining all-day battery life. New fitness algorithms provide more accurate workout metrics, while enhanced connectivity options keep you connected wherever you go. The aerospace-grade titanium case offers durability without adding weight. The new sleep apnea detection feature monitors breathing patterns during sleep to identify potential health concerns, while the stress management tools help you maintain mental wellbeing through guided breathing exercises and mindfulness prompts. The enhanced water resistance now supports diving up to 100 meters, with a dedicated diving computer app that tracks depth, duration, and water temperature. The improved GPS system with dual-frequency precision ensures accurate route tracking even in dense urban environments. With double the storage capacity of previous models, you can store more music, photos, and apps directly on your wrist.', 20, 'assets/img/appleWatchSeries10.webp', 26000, 1),
(6, 'AirPods 4', 'Experience immersive sound with the all-new Apple AirPods 4. Featuring advanced Active Noise Cancellation, these earbuds deliver crystal-clear audio while blocking out unwanted external noise. The redesigned acoustic architecture provides rich, detailed sound with enhanced bass response and crisp highs. Adaptive EQ automatically tunes music to your ear shape, while the new pressure-equalizing vent system ensures all-day comfort. With up to 7 hours of listening time (5 hours with ANC enabled) and additional 21 hours from the charging case, you\'ll enjoy your music all day. The H2 chip enables seamless device switching, hands-free Siri access, and personalized Spatial Audio with dynamic head tracking for a theater-like experience. The improved microphone array with voice isolation ensures crystal-clear calls even in noisy environments, while the redesigned stem provides more intuitive touch controls for playback and volume adjustment. The case now features USB-C charging, Find My integration with precision finding, and an IP54 rating for dust and water resistance. A quick 5-minute charge provides up to 1 hour of listening time when you\'re in a hurry, and the case supports both wired and wireless charging options for ultimate convenience.', 50, 'assets/img/airpods4.webp', 14500, 3),
(7, 'Apple Watch Series 9 Titanium Case', 'The Apple Watch Series 9 with Titanium Case combines premium materials with advanced technology. Featuring a lightweight yet durable titanium construction that\'s both corrosion-resistant and stronger than stainless steel, this premium watch offers exceptional comfort for all-day wear. The latest health monitoring capabilities include ECG, blood oxygen measurement, and temperature sensing for cycle tracking. The S9 chip delivers faster performance and a more responsive experience, while the ultra-bright Always-On Retina display ensures visibility in any lighting condition. With enhanced workout detection, improved GPS accuracy, and comprehensive sleep tracking, this watch is the perfect companion for an active, health-conscious lifestyle. The new Double Tap gesture recognition allows you to control the watch by tapping your index finger and thumb together, making one-handed operation more convenient than ever. The advanced neural engine processes health data on-device for enhanced privacy and faster insights. The sapphire crystal display offers superior scratch resistance, while the Digital Crown provides precise navigation with haptic feedback. Available in natural, space black, and gold titanium finishes, each watch comes with a specially treated surface that resists fingerprints and maintains its premium appearance over time.', 18, 'assets/img/appleWatchTitanium.webp', 36000, 1),
(8, 'Apple Watch Ultra 2', 'The Apple Watch Ultra 2 is engineered for adventure, exploration, and endurance. Built with premium materials including a titanium case, sapphire crystal display, and customizable Action button, this rugged watch withstands extreme conditions from high-altitude mountaineering to deep-water diving. The precision dual-frequency GPS provides accurate location tracking even in challenging environments, while the redesigned Compass app includes waypoints and backtracking. With up to 36 hours of battery life (72 hours in low-power mode), it supports multi-day adventures. The extra-bright 3000-nit display ensures visibility in direct sunlight, while the 86-decibel siren can alert others in emergency situations. Advanced metrics for running, swimming, cycling, and diving make it the ultimate tool for athletic performance. The enhanced night mode automatically activates in low light, using a red display that preserves night vision for astronomy and nighttime activities. The redesigned Depth app now includes decompression tracking for technical diving, while the new Trail Running workout type provides specialized metrics for off-road running. The titanium case features reinforced corners and a raised edge that protects the display from side impacts during extreme activities. The three-microphone array with beamforming technology ensures clear voice calls even in windy or noisy environments, making it perfect for communication during outdoor adventures.', 15, 'assets/img/appleWatchultra2.webp', 46000, 1),
(9, 'Beats Solo Buds', 'Beats Solo Buds deliver powerful, balanced sound in a sleek wireless design. Perfect for workouts and daily use with sweat resistance and secure-fit wingtips that keep your earbuds in place during intense activities. The custom acoustic architecture provides rich, detailed audio with punchy bass and clear highs. With up to 8 hours of listening time and an additional 16 hours from the pocket-sized charging case, you\'ll have music all day. One-touch pairing works seamlessly with both Apple and Android devices, while the built-in microphones with voice targeting ensure crystal-clear calls even in noisy environments. The intuitive touch controls let you manage music, calls, and voice assistants with simple taps. The proprietary driver design delivers the signature Beats sound profile with enhanced clarity across all frequencies, while the advanced digital signal processing automatically optimizes audio based on your listening environment. The ergonomic design has been tested across thousands of ear shapes to ensure a comfortable, secure fit for extended wear. The USB-C charging port provides quick power when needed, with a 5-minute Fast Fuel charge delivering up to 1 hour of playback. The Beats app for Android users enables additional customization options, including EQ presets and button remapping to suit your preferences.', 40, 'assets/img/beatssolobuds.webp', 13000, 3),
(10, 'Crystal UHD DU7000', 'The Crystal UHD DU7000 delivers stunning 4K clarity with advanced color technology. Experience immersive entertainment with powerful AI upscaling that transforms standard definition content into near-4K quality. The Crystal Processor 4K optimizes picture quality scene by scene, while HDR enhances contrast for greater depth and detail. Motion Xcelerator technology ensures smooth action even in fast-moving scenes, making it ideal for sports and gaming. The sleek, minimalist design features an ultra-thin bezel that blends seamlessly into any home environment. Smart TV capabilities include voice assistant compatibility, built-in streaming apps, and SmartThings integration to control your connected home devices. The Adaptive Sound automatically adjusts audio settings based on what you\'re watching for an optimized listening experience. The Object Tracking Sound Lite creates a more immersive audio experience by following the action on screen, while the Q-Symphony feature works in harmony with compatible soundbars for enhanced audio performance. The Gaming Hub provides easy access to cloud gaming services without requiring a console, while the Multi View feature lets you watch two content sources simultaneously. With AirSlim design, this TV maintains a sophisticated profile from any angle, and the solar-powered remote control eliminates the need for disposable batteries, reflecting a commitment to eco-friendly design.', 20, 'assets/img/crystaluhd.webp', 45000, 8),
(11, 'Galaxy Buds2 Pro', 'Samsung Galaxy Buds2 Pro brings premium sound quality with 24-bit Hi-Fi audio and intelligent Active Noise Cancellation. Designed for comfort and seamless connectivity with Galaxy devices, these earbuds feature a 15% smaller design with an ergonomic shape for a secure fit during extended wear. The intelligent ANC system automatically detects your voice and switches to ambient mode for conversations, then returns to noise cancellation when you stop speaking. With 360° Audio and Direct Multi-channel sound, you\'ll experience immersive spatial audio that moves with your head. IPX7 water resistance protects against sweat and rain, while the enhanced battery delivers up to 5 hours of playback with ANC on (18 hours total with the case). The matte finish case supports wireless charging and quick pairing with your Galaxy ecosystem. The custom-designed coaxial 2-way speaker separates high and low frequencies for exceptional clarity, while the new Voice Detect feature automatically lowers your music and enhances ambient sounds when you speak. Three microphones in each earbud work with the AI-based noise cancellation algorithm to filter out background noise during calls, ensuring your voice comes through clearly. The touch-sensitive outer surface provides intuitive controls for playback, calls, and noise cancellation modes, while the SmartThings Find feature helps locate misplaced earbuds even when they\'re inside their closed case.', 45, 'assets/img/galaxybuds2pro.webp', 14000, 3),
(12, 'iMac 24 M3', 'The iMac 24 with M3 chip brings vibrant colors and powerful performance to your desktop. Features a stunning 4.5K Retina display with True Tone technology that automatically adjusts the color temperature based on your environment for a more natural viewing experience. The M3 chip delivers up to 2x faster performance than previous models, with an 8-core CPU, up to 10-core GPU, and 16-core Neural Engine for blazing-fast processing and graphics capabilities. The advanced camera system includes a 1080p FaceTime HD camera with larger sensor, while the six-speaker sound system creates an impressive spatial audio experience. The ultra-thin design measures just 11.5mm thin, available in seven vibrant colors, and includes color-matched accessories. With up to 24GB unified memory and 2TB storage, this all-in-one desktop handles everything from everyday tasks to professional creative workflows. The studio-quality three-microphone array ensures crystal-clear voice capture for calls and recordings, while the improved thermal system maintains optimal performance even during intensive tasks. The nano-texture glass option reduces glare without affecting image quality, perfect for brightly lit environments. The color-matched Magic Keyboard now includes Touch ID for secure authentication and Apple Pay purchases, while the Magic Mouse and optional Magic Trackpad complete the wireless desktop experience. Two Thunderbolt/USB 4 ports and up to two USB 3 ports provide connectivity for external devices and displays.', 18, 'assets/img/imac.webp', 80000, 6),
(13, 'iPad 9th Gen', 'The iPad 9th Generation delivers powerful performance at an incredible value. Perfect for learning, working, and staying connected with its versatile features including the A13 Bionic chip that delivers 20% faster performance than its predecessor. The 10.2-inch Retina display with True Tone provides a comfortable viewing experience in any lighting condition. Center Stage keeps you perfectly framed during video calls as the 12MP Ultra Wide front camera automatically pans and zooms. Apple Pencil (1st generation) support enables note-taking, drawing, and marking up documents, while the Smart Keyboard transforms your iPad into a productive workstation. With all-day battery life and iPadOS, multitasking becomes effortless with Split View and Slide Over features. The Neural Engine in the A13 Bionic chip powers machine learning capabilities that enhance photos, AR experiences, and Siri interactions. The 8MP back camera captures detailed photos and 1080p HD video, perfect for scanning documents and creating content. With 64GB or 256GB storage options, you\'ll have plenty of space for apps, photos, and files. The durable aluminum design is built to last, while the Touch ID sensor provides secure authentication for apps and Apple Pay. With support for gigabit-class LTE on cellular models, you can stay connected even when Wi-Fi isn\'t available.', 45, 'assets/img/ipad9th.webp', 23000, 4),
(14, 'iPad 10th Gen', 'The iPad 10th Generation features an all-screen design with a 10.9-inch Liquid Retina display. Powered by the A14 Bionic chip for fast performance in a colorful design, this iPad delivers a 20% increase in CPU and 10% improvement in graphics over the previous generation. The landscape stereo speakers provide an immersive audio experience for movies and games. The USB-C port enables faster charging and connectivity with a wide range of accessories. The relocated front camera is now positioned along the landscape edge, making video calls more natural when the iPad is in horizontal orientation. Available in four vibrant colors, it supports the new Magic Keyboard Folio with a built-in trackpad and Apple Pencil (USB-C) for enhanced productivity and creativity. The 12MP Ultra Wide front camera features Center Stage to keep you perfectly framed during video calls, while the 12MP back camera captures detailed photos and 4K video. With all-day battery life and advanced security features including Touch ID integrated into the top button, this iPad balances performance, versatility, and value. Wi-Fi 6 provides faster wireless connectivity, and cellular models support 5G for on-the-go productivity.', 40, 'assets/img/ipad10th.webp', 29000, 4),
(15, 'iPad Air 4th Gen', 'The iPad Air 4th Generation combines powerful performance with a stunning 10.9-inch display. Featuring the A14 Bionic chip and support for Apple Pencil and Magic Keyboard, this versatile device bridges the gap between the standard iPad and iPad Pro. The Liquid Retina display with P3 wide color gamut and anti-reflective coating delivers vibrant visuals for both creative work and entertainment. Touch ID is integrated into the top button for secure authentication, while the USB-C port enables faster data transfer and connection to cameras, external displays, and other accessories. The 12MP back camera captures detailed photos and 4K video, making it perfect for scanning documents, AR experiences, and creative projects. Available in five elegant finishes, the iPad Air balances performance and portability for professionals and students alike. The 6-core CPU and 4-core GPU in the A14 Bionic chip handle demanding tasks with ease, from editing 4K videos to creating complex illustrations. The stereo speakers in landscape mode provide an immersive audio experience for movies, music, and games. With support for Wi-Fi 6 and optional 5G connectivity on cellular models, you can stay productive wherever you go. The 7MP front camera ensures clear video calls, while the Neural Engine enables advanced machine learning capabilities for enhanced photo editing, voice recognition, and AR experiences.', 25, 'assets/img/ipadair4th.webp', 35000, 4),
(16, 'iPad Air 13', 'The iPad Air 13 combines powerful performance with a stunning 13-inch display. Featuring the M2 chip and advanced features in a thin and light design, this larger iPad Air delivers the perfect balance of screen real estate and portability. The Liquid Retina XDR display offers extreme dynamic range with 1000 nits of full-screen brightness and 1600 nits peak for HDR content. ProMotion technology provides refresh rates up to 120Hz for ultra-smooth scrolling and responsiveness. The M2 chip with 8-core CPU and 10-core GPU handles demanding tasks from 4K video editing to 3D design with ease. Four-speaker audio adjusts to portrait or landscape orientation, while the 12MP Ultra Wide front camera with Center Stage keeps you perfectly framed during video calls. With support for Apple Pencil Pro and Magic Keyboard, it\'s the ultimate creative and productivity tool. The advanced display features P3 wide color, True Tone, and an anti-reflective coating for comfortable viewing in any environment. The Thunderbolt/USB 4 port enables high-speed connections to external displays, storage devices, and cameras, with transfer speeds up to 40Gbps. Face ID provides secure authentication and Apple Pay support, while the LiDAR Scanner enables immersive AR experiences and improved depth sensing for photography. Available in both Wi-Fi and 5G cellular models, this iPad Air offers connectivity options for every need.', 30, 'assets/img/ipadair13inch.webp', 43000, 4),
(17, 'iPad Mini 7th Gen', 'The iPad Mini 7th Generation combines powerful performance with ultra-portability. Perfect for reading, note-taking, and creative work on the go, this compact tablet features an 8.3-inch Liquid Retina display with P3 wide color and True Tone for an immersive visual experience. Powered by the A16 Bionic chip, it delivers desktop-class performance in a device that fits in one hand. The landscape stereo speakers provide rich, immersive sound, while the USB-C port enables connection to a vast ecosystem of accessories. Apple Pencil (2nd generation) support transforms the iPad Mini into the perfect digital notebook, sketchbook, or marking tool. With all-day battery life, 5G connectivity, and Center Stage video calling, this powerful mini tablet is the ultimate portable companion for professionals, students, and creatives. The 12MP Wide back camera captures stunning photos and 4K video, while the 12MP Ultra Wide front camera automatically keeps you centered during video calls. Touch ID integrated into the top button provides secure authentication, and the advanced Neural Engine powers machine learning features across the system. The compact design weighs just 293 grams, making it easy to hold for extended periods, perfect for reading e-books or browsing the web. Available in four sophisticated finishes, this iPad Mini combines premium design with exceptional performance in the most portable iPad form factor.', 25, 'assets/img/ipadmini7th.webp', 35000, 4),
(18, 'iPad Pro 11 M4', 'The iPad Pro 11 with M4 chip delivers unprecedented power and capability. Perfect for creative professionals and demanding workflows, this pro-level tablet features the groundbreaking M4 chip with 10-core CPU, 10-core GPU, and 16-core Neural Engine for desktop-class performance. The advanced Liquid Retina XDR display with ProMotion, P3 wide color, and True Tone delivers exceptional visual fidelity for photo editing and design work. The Thunderbolt/USB 4 port enables high-speed connections to external displays, storage, and other pro accessories. The LiDAR Scanner enhances AR experiences, while the Pro camera system with Wide and Ultra Wide lenses captures professional-quality photos and videos. With support for Apple Pencil Pro with hover detection and Magic Keyboard, this iPad Pro transforms into a complete mobile studio for the most demanding creative professionals. The new display technology offers mini-LED backlighting with over 10,000 LEDs for incredible contrast and brightness, making it perfect for HDR content creation and consumption. The advanced thermal design maintains peak performance during intensive tasks like 3D rendering or video editing. Face ID provides secure authentication with attention awareness for enhanced security. The four-speaker audio system automatically adjusts to the iPad\'s orientation, delivering studio-quality sound for music, movies, and video calls. With up to 2TB of storage and support for external drives, you\'ll never run out of space for your creative projects.', 25, 'assets/img/ipadpro11inch.webp', 60000, 4),
(19, 'iPhone 11', 'The iPhone 11 delivers exceptional value with its dual-camera system and A13 Bionic chip. Perfect for capturing life\'s moments with Night mode and stunning video capabilities, this durable smartphone features a 6.1-inch Liquid Retina HD display with True Tone for comfortable viewing in any lighting condition. The dual 12MP Ultra Wide and Wide cameras enable 2x optical zoom out, Portrait mode with advanced bokeh and Depth Control, and 4K video recording at 60 fps. The A13 Bionic chip with third-generation Neural Engine powers sophisticated photography features like Smart HDR and Deep Fusion for incredible detail and color. With all-day battery life, water resistance up to 2 meters for 30 minutes, and Face ID for secure authentication, the iPhone 11 continues to offer a premium experience at a mid-range price point. The front TrueDepth camera captures 12MP photos and 4K video, perfect for detailed selfies and FaceTime calls in any lighting condition. The Spatial Audio feature with Dolby Atmos creates an immersive sound experience for movies and music. The durable glass and aluminum design is available in six vibrant colors, while the improved IP68 water resistance protects against everyday spills. Wireless charging and fast-charge capability provide flexible power options, and the Ultra Wideband chip enables precise spatial awareness for enhanced AirDrop functionality and other location-based features.', 30, 'assets/img/iphone11.webp', 35000, 5),
(20, 'iPhone 12', 'The iPhone 12 features a powerful A14 Bionic chip and edge-to-edge OLED display. Experience 5G speed and advanced dual-camera system in a beautifully designed package with Ceramic Shield front cover that offers 4x better drop protection. The Super Retina XDR display delivers industry-leading color accuracy and brightness, while the Night mode on both Wide and Ultra Wide cameras captures stunning low-light photos. MagSafe enables a new ecosystem of easy-to-attach accessories and faster wireless charging. The A14 Bionic, the first 5nm chip in a smartphone, powers computational photography features like Deep Fusion and Smart HDR 3 for improved detail and dynamic range. With IP68 water resistance, Dolby Vision HDR video recording, and an aerospace-grade aluminum design available in five colors, the iPhone 12 represents a significant leap in smartphone technology. The flat-edge design is reminiscent of classic iPhone models while providing improved durability and grip. The OLED display offers 2532 x 1170 resolution at 460 ppi with HDR support and 1200 nits peak brightness for stunning visual quality even in bright sunlight. The Ultra Wide camera captures four times more scene, perfect for landscapes and group photos, while the improved Wide camera with f/1.6 aperture allows 27% more light for better low-light performance. The LiDAR Scanner on Pro models enables Night mode portraits and enhanced AR experiences with precise depth mapping.', 25, 'assets/img/iphone12.webp', 40000, 5),
(21, 'iPhone 13', 'The iPhone 13 features an advanced dual-camera system, A15 Bionic chip, and Super Retina XDR display. Experience exceptional performance and stunning photography capabilities with the redesigned camera system that captures 47% more light for better photos and videos in low light. Cinematic mode automatically creates beautiful depth effects and focus transitions in your videos. The A15 Bionic chip with 5-core GPU delivers lightning-fast performance and efficiency for demanding apps and games. The Super Retina XDR display is 28% brighter outdoors, making content easier to see even in bright sunlight. With improved battery life that provides up to 2.5 more hours of use compared to the iPhone 12, you can do more without worrying about running out of power. The Ceramic Shield front cover provides exceptional durability, while the IP68 rating ensures protection against water and dust. The advanced dual-camera system features sensor-shift optical image stabilization for smoother videos and sharper photos, even in motion. Photographic Styles allow you to customize the look of your images while preserving skin tones, and Smart HDR 4 intelligently adjusts contrast, color, and noise across different subjects in a scene. With 5G capability, you\'ll experience faster downloads and high-quality streaming, while the redesigned internal components allow for a larger battery and improved thermal management.', 35, 'assets/img/iphone13.webp', 45000, 5),
(22, 'iPhone 14 Plus', 'The iPhone 14 Plus combines a large 6.7-inch display with exceptional battery life. Featuring advanced camera capabilities and powerful performance for an enhanced user experience, this model offers the largest screen in the non-Pro iPhone lineup. The Super Retina XDR display delivers vibrant colors and sharp text, perfect for watching videos, browsing photos, or reading articles. Powered by the A15 Bionic chip with 5-core GPU, it handles demanding tasks with ease while maintaining energy efficiency. The advanced camera system includes a 12MP main camera with larger sensor and faster aperture, capturing stunning photos even in challenging lighting conditions. Photographic Styles and Smart HDR 4 provide creative control and balanced exposure across subjects. The new Action mode delivers smooth, steady video even when you\'re in motion, perfect for capturing dynamic moments. Emergency SOS via satellite enables messaging with emergency services when cellular and Wi-Fi coverage isn\'t available, while Crash Detection can automatically call for help when a severe car crash is detected. With all-day battery life that outlasts the standard iPhone 14 by up to 6 hours, this device is perfect for users who need a large display and extended usage between charges. The durable design features Ceramic Shield front cover, aerospace-grade aluminum, and water resistance up to 6 meters for 30 minutes.', 28, 'assets/img/iphone14plus.webp', 55000, 5),
(23, 'iPhone 15', 'The iPhone 15 features the powerful A16 Bionic chip and an advanced camera system with a 48MP main camera. Experience Dynamic Island, USB-C, and stunning photography capabilities in a refined design crafted from aerospace-grade aluminum and infused with color throughout the material. The 6.1-inch Super Retina XDR display offers exceptional brightness and clarity, while the Dynamic Island provides an intuitive way to see alerts and Live Activities without interrupting what you\'re doing. The 48MP main camera with quad-pixel sensor captures incredible detail, enabling 2x optical-quality zoom and 4K resolution at 24, 30, or 60 fps. The advanced image pipeline and Photonic Engine dramatically improve low-light performance across all cameras. The new Smart HDR system intelligently recognizes and optimizes different elements within a scene, from skin tones to the sky. The USB-C connector provides universal compatibility with a wide range of accessories and faster data transfer speeds. The A16 Bionic chip delivers exceptional performance and efficiency, powering advanced features like computational photography and immersive AR experiences. With improved battery life, enhanced durability with Ceramic Shield front cover, and IP68 water resistance, the iPhone 15 is designed to keep up with your active lifestyle. The new Roadside Assistance via satellite feature connects you with help even when cellular and Wi-Fi aren\'t available, providing peace of mind wherever your adventures take you.', 40, 'assets/img/iphone15.webp', 65000, 5),
(24, 'iPhone 16 Pro', 'The iPhone 16 Pro sets new standards with its A18 Pro chip, advanced camera system, and ProMotion display. Experience unprecedented power and professional-grade capabilities in a device engineered for the most demanding users. The 6.3-inch Super Retina XDR display with ProMotion technology offers adaptive refresh rates up to 120Hz for ultra-smooth scrolling and responsiveness, while the Always-On display shows glanceable information without waking the device. The pro camera system features a 48MP main camera with a larger sensor, a 12MP Ultra Wide camera with improved macro photography capabilities, and a 12MP Telephoto camera with 5x optical zoom for exceptional versatility. The new Camera Control button provides instant access to camera controls and settings with a single press. The A18 Pro chip with enhanced Neural Engine delivers desktop-class performance for demanding tasks like 4K video editing and 3D rendering, while maintaining impressive energy efficiency. The Titanium design is both lighter and stronger than previous Pro models, with a brushed finish that resists fingerprints. Advanced connectivity options include Wi-Fi 7, Thread networking for smart home devices, and satellite communications for emergency situations. The new spatial video recording capability captures immersive content viewable on Apple Vision Pro, while the improved Cinematic mode now supports 4K resolution at 30 fps with Dolby Vision. With up to 2TB of storage, all-day battery life, and enhanced durability including IP68 water resistance, the iPhone 16 Pro is the ultimate tool for professionals and enthusiasts alike.', 20, 'assets/img/iphone16Pro.webp', 90000, 5),
(25, 'Jabra Elite 85t', 'The Jabra Elite 85t delivers premium sound and adjustable noise cancellation with advanced 6-microphone technology for crystal-clear calls and superior ANC performance. These earbuds feature a semi-open design with pressure relief vents to prevent ear fatigue during extended listening sessions. The 12mm speakers—significantly larger than previous models—produce powerful bass and crisp highs with impressive clarity across all frequencies. The adjustable ANC lets you control exactly how much of the outside world you want to hear, with 11 levels ranging from full transparency to complete noise cancellation. The dedicated smartphone app provides extensive customization options, including a 5-band equalizer, sound presets, and personalized hearing profiles. With up to 5.5 hours of battery life with ANC on (7 hours with ANC off) and an additional 19.5 hours from the compact charging case, these earbuds keep up with your busy lifestyle. The wireless charging case supports Qi-certified chargers for added convenience, while the fast charge feature provides up to 1 hour of use from just 15 minutes of charging. The IPX4 rating ensures protection against sweat and light rain, making these earbuds suitable for workouts and outdoor activities. With Bluetooth 5.1 connectivity and multipoint pairing, you can connect to two devices simultaneously and seamlessly switch between them.', 28, 'assets/img/jabra85t.webp', 12000, 3),
(26, 'LG C3 OLED evo', 'The LG C3 OLED evo represents the pinnacle of OLED technology with perfect blacks and infinite contrast. Features advanced gaming features and AI-powered processing that elevates your viewing experience to new heights. The self-lit pixels provide pixel-level dimming for incredible contrast and color accuracy, while the α9 Gen6 AI Processor 4K uses deep learning algorithms to optimize picture and sound quality based on content type. Dolby Vision IQ and Dolby Atmos support create a cinematic experience in your living room, adjusting picture settings based on ambient light conditions and delivering immersive, room-filling sound. For gamers, the C3 offers a 0.1ms response time, NVIDIA G-SYNC compatibility, AMD FreeSync Premium, and four HDMI 2.1 ports supporting 4K gaming at 120Hz. The Game Optimizer menu provides quick access to all game-related settings, while the new Game Dashboard displays key information at a glance. The sleek, minimalist design features an almost bezel-less display and an elegant stand that complements any interior. WebOS 23 provides an intuitive smart TV experience with personalized content recommendations and easy access to streaming services. The Magic Remote with voice recognition allows for effortless navigation and content search, while the multi-view feature lets you watch content from two sources simultaneously. With built-in support for Apple AirPlay 2, Google Assistant, and Amazon Alexa, this TV seamlessly integrates with your smart home ecosystem.', 10, 'assets/img/lgoled.webp', 130000, 8),
(27, 'MacBook Air 15 M3', 'The MacBook Air 15 with M3 chip combines incredible performance with a stunning large display in an ultra-thin design. Perfect for everyday tasks and creative work, this MacBook Air features a gorgeous 15.3-inch Liquid Retina display with P3 wide color gamut and 500 nits of brightness for vibrant, true-to-life visuals. The M3 chip with 8-core CPU, up to 10-core GPU, and 16-core Neural Engine delivers exceptional performance and efficiency, handling everything from web browsing and document editing to photo and video editing with ease. The fanless design ensures completely silent operation, while the all-day battery life provides up to 18 hours of web browsing or 15 hours of video playback on a single charge. The advanced camera system includes a 1080p FaceTime HD camera with computational video processing for superior image quality during video calls, complemented by a three-microphone array with directional beamforming for clear voice capture. The four-speaker sound system with wide stereo and support for Spatial Audio creates an immersive listening experience for music and movies. The backlit Magic Keyboard includes a full-height function row and Touch ID for secure authentication and Apple Pay purchases. With two Thunderbolt/USB 4 ports, MagSafe charging, and a 3.5mm headphone jack, this MacBook Air offers versatile connectivity options. Available in four elegant finishes and measuring just 11.5mm thin, it combines performance, portability, and style in a remarkably lightweight package.', 25, 'assets/img/macbookair.webp', 70000, 6),
(28, 'MacBook Pro 14 M3', 'The MacBook Pro 14 with M3 chip delivers extraordinary performance and efficiency. Features a stunning Liquid Retina XDR display and pro-level capabilities for demanding workflows, making it the perfect tool for creative professionals and power users. The 14.2-inch display offers extreme dynamic range with 1000 nits of sustained brightness (1600 nits peak for HDR content) and ProMotion technology with adaptive refresh rates up to 120Hz for ultra-smooth scrolling and responsive gaming. The M3 chip, built on 3nm technology, features an 8-core CPU with four performance cores and four efficiency cores, up to 10-core GPU with hardware-accelerated ray tracing, and 16-core Neural Engine for advanced machine learning tasks. The advanced thermal system ensures sustained performance during intensive tasks like 3D rendering, video encoding, or complex simulations. The Magic Keyboard provides a comfortable typing experience with 1mm of key travel, while the expansive Force Touch trackpad offers precise cursor control and support for Multi-Touch gestures. The comprehensive connectivity options include three Thunderbolt 4 ports, HDMI port, SDXC card slot, MagSafe 3 charging port, and 3.5mm headphone jack with support for high-impedance headphones. The six-speaker sound system with force-cancelling woofers delivers room-filling sound with wide stereo separation, while the studio-quality three-microphone array captures your voice with exceptional clarity. With up to 22 hours of battery life, this MacBook Pro keeps you productive throughout the day, and fast charging provides 50% charge in just 30 minutes.', 15, 'assets/img/macbookpro.webp', 90000, 6),
(29, 'Mac mini M2 Pro', 'The Mac mini with M2 Pro chip brings pro-level performance to a compact desktop. Perfect for content creation, development, and intensive workloads, this powerful computer packs extraordinary capabilities into a design that measures just 7.7 inches square and 1.4 inches thin. The M2 Pro chip features up to 12-core CPU with eight performance cores and four efficiency cores, up to 19-core GPU, and 16-core Neural Engine, delivering exceptional performance for demanding tasks like photo and video editing, 3D rendering, and software development. With support for up to 32GB of unified memory and up to 8TB of SSD storage, this Mac mini handles large files and complex projects with ease. The comprehensive connectivity options include four Thunderbolt 4 ports, two USB-A ports, HDMI port supporting 8K resolution, Gigabit Ethernet (configurable to 10Gb Ethernet), and a 3.5mm headphone jack. The advanced thermal system ensures optimal performance even during intensive tasks, while maintaining the Mac mini\'s characteristic quiet operation. With Wi-Fi 6E and Bluetooth 5.3, you\'ll enjoy fast wireless connectivity for peripherals and networking. The Mac mini supports up to three displays simultaneously, including two 6K displays over Thunderbolt and one 4K display over HDMI. macOS provides a seamless experience with powerful built-in apps, industry-leading privacy features, and compatibility with iPhone and iPad. The energy-efficient design uses up to 40% less energy in low-power mode, reflecting Apple\'s commitment to environmental responsibility.', 20, 'assets/img/macmini.webp', 60000, 6),
(30, 'Mac Pro M2 Ultra', 'The Mac Pro with M2 Ultra represents the pinnacle of Apple silicon performance. Engineered for extreme workflows and unprecedented expandability, this professional workstation combines the raw power of the M2 Ultra chip with a modular design that supports extensive customization. The M2 Ultra chip features a 24-core CPU with 16 performance cores and 8 efficiency cores, up to 76-core GPU, and 32-core Neural Engine, delivering extraordinary performance for the most demanding professional applications. With support for up to 192GB of unified memory with 800GB/s memory bandwidth, this Mac Pro handles massive datasets and complex simulations with ease. The tower enclosure provides exceptional thermal management and easy access to components, with eight PCIe expansion slots for additional capabilities like more storage, audio interfaces, or networking cards. The comprehensive connectivity options include eight Thunderbolt 4 ports, two USB-A ports, two 10Gb Ethernet ports, and a 3.5mm headphone jack with support for high-impedance headphones. The Mac Pro supports up to eight displays, including six 6K Pro Display XDRs over Thunderbolt and two 4K displays over HDMI. The optional Afterburner card accelerates ProRes and ProRes RAW video decoding, perfect for film and video professionals working with high-resolution footage. With macOS, you get access to professional apps like Final Cut Pro, Logic Pro, and Xcode, all optimized for Apple silicon. The Mac Pro is designed and built with exceptional attention to detail, from the precision-machined aluminum housing to the whisper-quiet cooling system, making it the ultimate tool for professionals pushing the boundaries of what\'s possible.', 5, 'assets/img/macpro.webp', 250000, 6),
(31, 'Mac Studio M2 Ultra', 'The Mac Studio with M2 Ultra delivers groundbreaking performance for professional workflows. Built for the most demanding tasks in a compact design, this powerhouse computer combines extraordinary capabilities with versatile connectivity in a form factor that fits perfectly on your desk. The M2 Ultra chip—essentially two M2 Max chips connected via Apple\'s UltraFusion architecture—features a 24-core CPU, up to 76-core GPU, and 32-core Neural Engine, delivering unprecedented performance for tasks like rendering complex 3D scenes, compiling massive codebases, or working with multiple streams of 8K video. With support for up to 192GB of unified memory and up to 8TB of SSD storage, the Mac Studio handles massive projects with ease. The innovative thermal system with over 4,000 precisely machined perforations in the bottom and back works in concert with the internal fans to ensure optimal cooling while maintaining quiet operation. The comprehensive connectivity options include six Thunderbolt 4 ports, two USB-A ports, HDMI port, 10Gb Ethernet, and a 3.5mm headphone jack on the back, plus two USB-C ports and an SDXC card slot conveniently located on the front. The Mac Studio supports up to five displays, including four 6K Pro Display XDRs over Thunderbolt and one 4K display over HDMI. At just 7.7 inches square and 3.7 inches tall, the Mac Studio takes up minimal desk space while delivering workstation-class performance. With macOS, you get access to professional apps optimized for Apple silicon, creating a seamless and powerful creative environment for the most demanding professionals.', 10, 'assets/img/macstudio.webp', 150000, 6),
(32, 'MSI Claw A1M', 'The MSI Claw A1M is a powerful handheld gaming PC featuring Intel Core Ultra processors. Experience PC gaming on the go with exceptional performance and versatility, combining the power of a gaming laptop with the convenience of a portable console. The 7-inch Full HD (1920 x 1080) IPS display with 120Hz refresh rate and 500 nits brightness delivers smooth, vibrant visuals for an immersive gaming experience. Powered by Intel Core Ultra 7 155H processor with Intel Arc graphics, this handheld device handles demanding AAA games with impressive frame rates and visual fidelity. The ergonomic design features customizable RGB lighting, precision analog thumbsticks with hall effect sensors to prevent drift, responsive face buttons, and programmable back buttons for a competitive edge. The comprehensive cooling system with dual fans and heat pipes ensures optimal performance during extended gaming sessions while maintaining comfortable surface temperatures. With 16GB LPDDR5 RAM and up to 1TB PCIe Gen4 SSD, the Claw offers ample memory and storage for your game library and quick loading times. The 53Whr battery provides up to 2 hours of intensive gaming or 8 hours of video playback, while the 65W USB-C fast charging quickly replenishes power when needed. Connectivity options include Wi-Fi 7, Bluetooth 5.4, USB4 Type-C port, microSD card reader, and 3.5mm audio jack. The MSI Center for Handhelds software provides easy access to game libraries across multiple platforms, performance optimization tools, and customizable control settings. Running Windows 11, this versatile device gives you access to your entire PC game library, productivity applications, and streaming services in a portable form factor.', 20, 'assets/img/msiclaw.webp', 50000, 2),
(33, 'Nvision 32\" Smart TV', 'The Nvision 32\" Smart TV offers excellent value with smart features and crisp HD display. Perfect for bedrooms and small living spaces, this compact television delivers an impressive viewing experience without breaking the bank. The 32-inch HD display (1366 x 768 resolution) provides clear, detailed images with vibrant colors and good contrast for everyday viewing. The slim bezel design maximizes screen real estate while maintaining a modern aesthetic that complements any interior. Powered by a quad-core processor, the smart TV interface offers smooth navigation and quick app loading times. Pre-installed streaming apps include Netflix, YouTube, Prime Video, and more, giving you instant access to thousands of movies, TV shows, and videos. The built-in Wi-Fi connects easily to your home network, while the Ethernet port provides a stable wired connection option. The comprehensive connectivity options include three HDMI ports for gaming consoles and external devices, two USB ports for media playback, component/composite inputs for legacy devices, and a digital optical output for connecting to sound systems. The down-firing speakers deliver clear dialogue and decent sound quality for casual viewing, with multiple sound modes optimized for different content types. The included remote control features dedicated buttons for popular streaming services, allowing for quick access to your favorite content. With low power consumption and an energy-efficient design, this smart TV helps reduce electricity costs while providing reliable performance. The intuitive on-screen menu system makes setup and customization simple, even for users who aren\'t technically inclined, making this Nvision TV an excellent choice for budget-conscious consumers who don\'t want to sacrifice features or quality.', 50, 'assets/img/nvision.webp', 10000, 8);
INSERT INTO `products` (`product_id`, `product_name`, `description`, `stocks`, `image_path`, `price`, `category_id`) VALUES
(34, 'PS5 Slim', 'The PS5 Slim delivers next-gen gaming in a more compact design. Experience lightning-fast loading, stunning 4K graphics, and immersive DualSense controller features in a console that\'s 30% smaller and 18% lighter than the original PS5. The custom AMD Ryzen CPU with 8 cores and 3.5GHz clock speed works in tandem with the 10.3 teraflop AMD Radeon RDNA 2 GPU to deliver exceptional gaming performance with ray tracing, 4K resolution at up to 120fps, and HDR support. The revolutionary SSD provides 825GB of storage with blazing-fast 5.5GB/s raw data transfer speeds, virtually eliminating loading screens and enabling seamless game worlds. The innovative DualSense wireless controller features haptic feedback that simulates different sensations, adaptive triggers that adjust tension based on in-game actions, and a built-in microphone for quick communication. Tempest 3D AudioTech creates immersive soundscapes that place you at the center of the action, with hundreds of sound sources precisely positioned around you. The redesigned console now features a detachable disc drive that can be added or removed based on your preferences, providing greater flexibility and future-proofing. Backward compatibility supports thousands of PS4 games, many with improved loading speeds and frame rates. The comprehensive connectivity options include Wi-Fi 6, Bluetooth 5.1, HDMI 2.1 port supporting 8K output, and three USB ports. With access to PlayStation exclusive titles, PlayStation Plus subscription service, and a growing library of next-generation games, the PS5 Slim represents the future of gaming in a more space-efficient design.', 35, 'assets/img/ps5slim.webp', 30000, 2),
(35, 'Samsung QLED Q60C', 'The Samsung QLED Q60C brings quantum dot technology for brilliant color and contrast. Features advanced gaming capabilities and smart home integration in a sleek, modern design that enhances any living space. The Quantum Processor Lite optimizes picture quality in real-time, upscaling content to 4K resolution and enhancing color, contrast, and clarity. 100% Color Volume with Quantum Dot technology delivers over a billion shades of color that stay true-to-life regardless of brightness level. Motion Xcelerator ensures smooth action in fast-paced scenes, making it ideal for sports and gaming, while Dual LED backlighting adjusts color temperature for more natural images. The Gaming Hub provides easy access to cloud gaming services without requiring a console, and Game Bar displays key gaming information at a glance. With FreeSync support, Auto Low Latency Mode, and Motion Xcelerator, gamers enjoy responsive gameplay with minimal input lag and motion blur. The comprehensive smart features include built-in voice assistants (Bixby, Amazon Alexa, and Google Assistant), SmartThings integration for controlling compatible smart home devices, and Multi View for watching content from two sources simultaneously. The slim design with AirSlim profile and minimal bezels creates a sophisticated look from any angle, while the solar-powered SolarCell Remote eliminates the need for disposable batteries. With Object Tracking Sound Lite, Q-Symphony compatibility with Samsung soundbars, and adaptive sound technology that optimizes audio based on content type, this QLED TV delivers an immersive audiovisual experience for movies, shows, sports, and games.', 15, 'assets/img/samsungqled.webp', 90000, 8),
(36, 'Sony BRAVIA XR A80L', 'The Sony BRAVIA XR A80L delivers revolutionary cognitive processing and immersive sound. Experience true-to-life picture quality with XR OLED technology that combines the self-illuminating pixels of OLED with Sony\'s Cognitive Processor XR, which analyzes and optimizes hundreds of thousands of elements on screen just as the human brain does. The result is unprecedented contrast with pure blacks, natural colors, and exceptional brightness. XR OLED Contrast Pro enhances color and contrast in bright areas while maintaining deep blacks, creating a more dynamic and realistic image. The XR Motion Clarity technology ensures smooth, blur-free movement in fast-paced scenes without sacrificing brightness. The innovative Acoustic Surface Audio+ turns the entire screen into a speaker, with actuators behind the panel that vibrate to produce sound from the exact location where the action is happening on screen. This is complemented by two subwoofers for powerful bass, creating a truly immersive audio experience without additional speakers. For gamers, the A80L offers HDMI 2.1 features including 4K/120Hz, Variable Refresh Rate, Auto Low Latency Mode, and Auto HDR Tone Mapping for PlayStation 5. The exclusive BRAVIA CORE streaming service provides access to a collection of Sony Pictures movies in near-lossless UHD Blu-ray quality. Google TV integration offers personalized content recommendations and seamless access to over 700,000 movies and TV episodes from your favorite streaming services. With hands-free voice search, Apple AirPlay 2 support, and HomeKit compatibility, this premium OLED TV combines cutting-edge technology with intuitive usability in an elegant design with flush surface bezel and versatile multi-position stand options.', 8, 'assets/img/sonytv.webp', 150000, 8),
(37, 'Sony WF-1000XM4', 'The Sony WF-1000XM4 sets new standards in wireless noise cancelling earbuds with industry-leading noise cancellation and exceptional sound quality powered by the V1 processor. These premium earbuds feature newly designed 6mm drivers with increased magnet volume and high compliance diaphragm that deliver rich, clear sound with powerful bass and detailed highs. The Integrated Processor V1 works in conjunction with dual noise sensor microphones and noise isolation eartips to provide unparalleled noise cancellation, especially effective against mid to high-frequency noise like human voices and environmental sounds. The Adaptive Sound Control automatically adjusts ambient sound settings based on your location and activity, while Speak-to-Chat temporarily pauses music and lets in ambient sound when you start speaking. High-Resolution Audio Wireless and LDAC codec support allow for transmission of approximately three times more data than conventional Bluetooth audio, preserving the detail of your music. The redesigned earbuds are 10% smaller than the previous generation, with an ergonomic shape and foam eartips that provide a secure, comfortable fit for extended listening sessions. With 8 hours of battery life with noise cancellation enabled (12 hours with NC off) and an additional 16 hours from the compact charging case, these earbuds keep up with your busy lifestyle. The case supports wireless charging and quick charge, providing 60 minutes of playback from just 5 minutes of charging. IPX4 water resistance protects against sweat and rain, while the beam-forming microphones and bone conduction sensor ensure crystal-clear call quality by detecting voice vibrations and filtering out ambient noise.', 30, 'assets/img/sonyxm4.webp', 16000, 3),
(38, 'Steam Deck', 'The Steam Deck is a powerful handheld gaming PC that lets you take your Steam library on the go. Features custom AMD APU optimized for handheld gaming, combining a 4-core/8-thread Zen 2 CPU with 8 RDNA 2 compute units for graphics, delivering more than enough performance to run the latest AAA games smoothly. The 7-inch optically bonded LCD touchscreen with 1280 x 800 resolution and 60Hz refresh rate provides vibrant visuals and responsive touch controls, while the anti-glare etched glass on premium models reduces reflections for comfortable outdoor use. The comprehensive control system includes dual analog sticks with capacitive touch, haptic feedback, gyroscope for motion control, and four assignable grip buttons on the back, giving you console-level precision and customization options. The 40Whr battery provides 2-8 hours of gameplay depending on the intensity of the games, while the custom SteamOS 3.0 (based on Arch Linux) optimizes performance and battery life while providing a console-like interface designed for handheld use. With 16GB of LPDDR5 RAM and options for 64GB eMMC, 256GB NVMe SSD, or 512GB high-speed NVMe SSD storage, plus microSD card expansion, you\'ll have plenty of space for your game library. The versatile connectivity options include Bluetooth 5.0, dual-band Wi-Fi, USB-C port with DisplayPort 1.4 Alt-mode support for connecting to external displays, and a 3.5mm headphone jack. The Steam Deck isn\'t just a gaming device—it\'s a full PC that can be connected to monitors, keyboards, and mice, or even installed with Windows, making it a versatile portable computing solution for gaming and beyond.', 15, 'assets/img/steamdeck.webp', 40000, 2),
(39, 'Nintendo Switch OLED', 'The Nintendo Switch OLED Model features a vibrant 7-inch OLED screen, enhanced audio, and a wider adjustable stand for the ultimate portable gaming experience. The OLED display delivers more vibrant colors and higher contrast compared to the LCD screen on the standard model, making games look more vivid and immersive whether you\'re playing in handheld mode or tabletop mode. The wider adjustable stand provides greater stability and can be positioned at various angles for comfortable viewing during multiplayer sessions. The enhanced audio system produces clearer sound when playing in handheld or tabletop mode, creating a more immersive gaming experience even without headphones. The redesigned dock includes a wired LAN port for more stable online play when in TV mode, while the internal storage has been doubled to 64GB, giving you more space for digital games and content. The system maintains the versatility that made the original Switch popular, with three play modes: TV mode for big-screen gaming at home, tabletop mode for multiplayer gaming anywhere, and handheld mode for on-the-go play. The Joy-Con controllers feature HD rumble, IR Motion Camera, and accelerometers for intuitive control across a wide variety of games. With access to Nintendo\'s extensive library of first-party exclusives like The Legend of Zelda, Mario, Animal Crossing, and Pokémon, plus thousands of third-party titles, the Switch OLED offers something for every type of player. The improved battery life provides approximately 4.5 to 9 hours of gameplay on a single charge, depending on the game and usage conditions, making it perfect for long gaming sessions away from home.', 40, 'assets/img/switch.webp', 20000, 2),
(40, 'Wanbo T2 Max', 'The Wanbo T2 Max delivers stunning visuals in a portable form factor. Perfect for movies, gaming, and presentations with its advanced features, this compact projector combines performance and convenience in an elegant design. The Full HD resolution (1920 x 1080) ensures sharp, detailed images up to 120 inches, while the 550 ANSI lumens brightness provides vivid colors and good visibility even in rooms with moderate ambient light. The advanced LED light source offers 30,000 hours of lamp life and superior color accuracy compared to traditional lamp projectors. The intelligent automatic keystone correction and focus adjustment make setup effortless—simply place the projector, and it automatically calibrates for a perfectly rectangular image. The built-in Android operating system provides access to popular streaming apps like Netflix, YouTube, and Prime Video without requiring external devices, while the dual-band Wi-Fi and Bluetooth 5.0 ensure stable wireless connectivity. The comprehensive connectivity options include HDMI, USB, and audio output, allowing connection to gaming consoles, laptops, smartphones, and external speakers. The integrated 5W stereo speakers deliver surprisingly robust sound for casual viewing, while the 3.5mm audio output and Bluetooth audio support provide options for enhanced sound when needed. The compact design weighing just 2.2 pounds makes it truly portable, while the elegant fabric-covered exterior adds a touch of sophistication to any space. With low fan noise (less than 30dB) and an eco-friendly power-saving mode, this projector provides an immersive viewing experience without distraction. The intuitive remote control and smartphone app offer convenient operation, making the Wanbo T2 Max an excellent choice for entertainment enthusiasts seeking quality and portability.', 20, 'assets/img/t2max.webp', 25000, 7),
(41, 'Wanbo T2 Ultra', 'The Wanbo T2 Ultra is a premium projector offering exceptional brightness and image quality. Features advanced AI-powered image enhancement and smart home integration in a sophisticated design that elevates any entertainment space. The native 1080p resolution with support for 4K input delivers crisp, detailed images up to 150 inches, while the impressive 800 ANSI lumens brightness ensures vibrant colors and good visibility even in rooms with ambient light. The MEMC (Motion Estimation, Motion Compensation) technology reduces motion blur in fast-moving scenes, making it ideal for sports and action movies. The AI-powered image enhancement automatically optimizes brightness, contrast, and color saturation based on content type and ambient lighting conditions, ensuring the best possible image quality in any environment. The advanced auto-focus and auto keystone correction with obstacle avoidance intelligently adjust the projection to create a perfect rectangular image, even when the projector is placed at an angle or when there are objects in the projection path. The comprehensive connectivity options include dual HDMI 2.0 ports, USB 3.0, audio output, and Ethernet, providing versatile connection options for all your devices. The built-in Android TV system offers access to thousands of apps from the Google Play Store, while Google Assistant integration enables voice control of the projector and compatible smart home devices. The premium Harman Kardon speakers deliver room-filling sound with rich bass and clear dialogue, eliminating the need for external speakers in most situations. With Wi-Fi 6 and Bluetooth 5.2, this projector ensures fast, stable wireless connectivity for streaming and screen mirroring. The elegant design with premium materials and attention to detail makes the T2 Ultra a stylish addition to any home, while the whisper-quiet cooling system (less than 26dB) ensures nothing distracts from your viewing experience.', 15, 'assets/img/t2ultra.webp', 35000, 7),
(42, 'Wanbo T3 Pro', 'The Wanbo T3 Pro delivers professional-grade projection with advanced features. Perfect for home theater and business presentations, this versatile projector combines exceptional image quality with comprehensive connectivity options and intelligent features. The native 1080p resolution with HDR10 support delivers crisp, detailed images with enhanced contrast and color depth, while the 1200 ANSI lumens brightness ensures vibrant visuals even in environments with moderate ambient light. The advanced LED light source with 30,000 hours of lamp life provides consistent color accuracy and brightness throughout its lifespan. The motorized zoom and focus with 1.3x optical zoom allow for flexible placement options, while the lens shift feature enables perfect image alignment without moving the projector. The intelligent 6-point keystone correction ensures a perfectly rectangular image even when the projector is placed at extreme angles. The comprehensive connectivity options include dual HDMI 2.0 ports with HDCP 2.2 support, USB 3.0, RS-232 for integration with control systems, optical audio output, and Ethernet port for stable network connection. The built-in dual-band Wi-Fi and Bluetooth 5.0 provide reliable wireless connectivity for streaming and audio transmission. The advanced color management system with multiple picture modes offers precise calibration options for different content types and viewing environments. The integrated 10W stereo speakers with Dolby Audio support deliver impressive sound quality for presentations and casual viewing, while the 3D compatibility allows for immersive viewing of compatible content. The intuitive on-screen menu system and backlit remote control make operation simple even in darkened rooms. With low fan noise (less than 28dB in eco mode) and an energy-efficient design, the Wanbo T3 Pro provides a premium projection experience for both home entertainment and professional applications.', 18, 'assets/img/t3pro.webp', 40000, 7),
(43, 'Wanbo T6 Max', 'The Wanbo T6 Max is a flagship projector offering cinema-quality projection. Features state-of-the-art laser technology and premium audio system that transform your living room into a true home theater experience. The 4K UHD resolution (3840 x 2160) delivers exceptional clarity and detail, while the advanced RGB laser light source with 2500 ANSI lumens brightness produces stunning colors with 107% coverage of the BT.2020 color gamut—significantly wider than standard projectors. The laser phosphor technology provides 25,000 hours of maintenance-free operation and instant on/off capability without warm-up or cool-down periods. The advanced lens system with motorized 1.6x zoom, focus, and lens shift offers flexible installation options, while the intelligent auto-calibration system uses a built-in camera to automatically adjust focus, keystone, and color accuracy for optimal image quality. The premium audio system developed in collaboration with renowned sound engineers features dual 15W speakers with dedicated woofers and tweeters, creating room-filling sound with rich bass and clear dialogue. The comprehensive connectivity options include triple HDMI 2.1 ports with eARC support, USB-C with DisplayPort Alt Mode, dual USB 3.0 ports, optical audio output, and Ethernet. The advanced video processing engine includes frame interpolation technology for smooth motion, dynamic contrast enhancement for deeper blacks, and AI-powered scene recognition that optimizes picture settings based on content type. The built-in streaming platform provides access to popular services in 4K HDR quality, while the voice-controlled remote simplifies navigation. With ultra-low input lag mode for gaming, 3D support, and ISF certification for professional calibration, the T6 Max delivers a premium viewing experience for movies, sports, gaming, and more. The elegant design with premium materials and attention to detail makes this projector a sophisticated addition to any home theater setup.', 10, 'assets/img/t6max.webp', 50000, 7),
(44, 'Wanbo Dali 1', 'The Wanbo Dali 1 is a compact and stylish projector perfect for home entertainment. Features Full HD resolution and smart connectivity options in an artistic design inspired by Salvador Dali\'s surrealist aesthetics. The native 1080p resolution ensures sharp, detailed images up to 100 inches, while the 500 ANSI lumens brightness provides vibrant colors for evening viewing. The unique artistic design features flowing curves and premium fabric covering that make it a decorative piece even when not in use—a refreshing departure from the utilitarian look of traditional projectors. The intelligent auto keystone correction and focus adjustment make setup effortless, while the built-in gyroscope automatically adjusts the image when the projector is moved. The omnidirectional projection capability allows you to project onto ceilings, walls, or even floors, creating immersive viewing experiences in any direction. The built-in Android operating system provides access to popular streaming apps, while the dual-band Wi-Fi and Bluetooth connectivity ensure stable wireless performance. The integrated 5W stereo speakers deliver surprisingly good sound for casual viewing, while the 3.5mm audio output and Bluetooth audio support provide options for enhanced sound when needed. The comprehensive connectivity options include HDMI, USB, and audio output, allowing connection to various devices. The portable design weighing just 2 pounds and the built-in 10,000mAh battery providing up to 3 hours of wireless projection make it perfect for impromptu movie nights indoors or outdoors. With low fan noise (less than 28dB) and an eco-friendly power-saving mode, this projector provides an immersive viewing experience without distraction, all wrapped in a conversation-starting design that blends technology with artistic expression.', 25, 'assets/img/dali1.webp', 20000, 7),
(45, 'Wanbo X1 Pro Max', 'The Wanbo X1 Pro Max represents the pinnacle of projection technology. Features revolutionary 8K processing and advanced AI upscaling that deliver unprecedented image quality for the most discerning home theater enthusiasts. The native 4K (3840 x 2160) resolution with 8K upscaling provides extraordinary detail and clarity, while the triple laser light source with 3000 ANSI lumens brightness and 98% Rec.2020 color coverage produces cinema-quality images with exceptional color accuracy and contrast. The advanced AI-powered image processing analyzes each frame in real-time, enhancing detail, reducing noise, and optimizing contrast for different content types. The precision-engineered glass lens array with 1.8x motorized zoom and extensive lens shift capabilities enables flexible installation options without image distortion. The revolutionary dynamic iris system adjusts light output 120 times per second, achieving a contrast ratio of 2,000,000:1 for inky blacks and brilliant highlights that rival OLED displays. The comprehensive connectivity options include triple HDMI 2.1 ports with 48Gbps bandwidth supporting 8K@60Hz and 4K@120Hz, eARC, VRR for gaming, USB-C with DisplayPort Alt Mode and 100W power delivery, and professional-grade inputs including SDI for broadcast equipment. The reference-quality audio system features quad speakers tuned by acoustic engineers, with dedicated amplifiers for each driver, creating immersive sound with precise imaging and dialogue clarity. The advanced thermal management system with liquid cooling ensures consistent performance and whisper-quiet operation even during extended use. The premium aluminum chassis with precision CNC machining not only provides durability and heat dissipation but also creates a sophisticated aesthetic worthy of high-end home theaters. With ISF and CalMAN certification for professional calibration, Filmmaker Mode for preserving directors\' creative intent, and comprehensive HDR support including Dolby Vision, HDR10+, and HLG, the X1 Pro Max delivers a truly reference-quality projection experience for the most demanding cinephiles.', 5, 'assets/img/x1.webp', 70000, 7),
(46, 'Xbox Series S', 'The Xbox Series S delivers next-gen performance in the smallest Xbox ever. Perfect for digital gaming with fast loading times and smooth gameplay, this compact console packs impressive capabilities into a design that\'s 60% smaller than the Xbox Series X. The custom AMD RDNA 2 GPU with 4 TFLOPS of processing power and 10GB GDDR6 memory delivers consistent 1440p gaming at up to 120fps, with support for 4K upscaling for compatible displays. The custom AMD Zen 2 CPU with 8 cores running at 3.6GHz ensures responsive gameplay and quick multitasking between games and apps. The 512GB custom NVMe SSD provides lightning-fast load times and enables Quick Resume, allowing you to seamlessly switch between multiple games and continue exactly where you left off. The all-digital design focuses on digital downloads and Xbox Game Pass, eliminating the need for physical discs while reducing size and cost. Xbox Velocity Architecture optimizes system performance, enabling features like DirectStorage for faster game asset streaming and Sampler Feedback Streaming for more detailed textures. The comprehensive backward compatibility supports thousands of games across four generations of Xbox, many with improved resolution, frame rates, and Auto HDR. The redesigned Xbox Wireless Controller features textured grips, improved ergonomics, and a dedicated share button for capturing and sharing gameplay moments. With support for Dolby Vision and Dolby Atmos, Variable Refresh Rate, and Auto Low Latency Mode, this console delivers premium gaming features at an accessible price point. The sleek white design with the distinctive black cooling vent looks modern and stylish in any entertainment setup, while consuming significantly less power than previous generation consoles.', 30, 'assets/img/xboxseriess.webp', 20000, 2),
(47, 'Xbox Series X', 'The Xbox Series X is Microsoft\'s most powerful console ever. Experience true 4K gaming, lightning-fast load times, and stunning graphics with ray tracing in a device engineered for the ultimate gaming performance. The custom AMD RDNA 2 GPU with 12 TFLOPS of processing power—twice that of the Xbox One X—delivers consistent 4K gaming at 60fps, with support for up to 120fps for compatible games and displays. The custom AMD Zen 2 CPU with 8 cores running at 3.8GHz ensures responsive gameplay and seamless multitasking. The revolutionary 1TB custom NVMe SSD virtually eliminates loading screens, reducing wait times from minutes to seconds, while the innovative Quick Resume feature allows you to seamlessly switch between multiple games and continue exactly where you left off. The advanced cooling system features a split motherboard design and unified air flow path, allowing the console to deliver maximum performance while remaining whisper-quiet. Xbox Velocity Architecture optimizes every aspect of the system, enabling larger, more dynamic game worlds and innovative features like DirectStorage and Sampler Feedback Streaming. The comprehensive backward compatibility supports thousands of games across four generations of Xbox, many with improved resolution, frame rates, and Auto HDR. The redesigned Xbox Wireless Controller features textured grips, improved ergonomics, and a dedicated share button for capturing and sharing gameplay moments. With support for Dolby Vision and Dolby Atmos, Variable Refresh Rate, and Auto Low Latency Mode, this console delivers a premium audiovisual experience for games and media. The distinctive vertical tower design with precision-engineered venting and subtle green highlights creates a bold yet elegant presence in your entertainment setup, symbolizing the uncompromising power contained within.', 25, 'assets/img/xboxseriesx.webp', 35000, 2),
(48, 'Xiaomi Smart TV A 2025', 'The Xiaomi Smart TV A 2025 combines cutting-edge technology with elegant design. Features AI-powered picture quality and immersive sound in a premium package that elevates your home entertainment experience. The 4K UHD display with Quantum Dot technology delivers vibrant colors with over a billion color combinations and exceptional brightness, while the full array local dimming with hundreds of independently controlled zones ensures deep blacks and precise highlights for stunning HDR content. The MediaTek premium processor optimizes performance across the system, from smooth UI navigation to advanced picture processing. The AI Picture Engine analyzes content in real-time, enhancing detail, color, and contrast based on the scene, while the MEMC technology ensures smooth motion in fast-paced action sequences and sports. The bezel-less metal design with diamond-cut edges and premium aluminum stand creates a sophisticated aesthetic that complements any interior design. The comprehensive connectivity options include triple HDMI 2.1 ports with eARC and ALLM support, dual USB ports, optical audio output, and Ethernet, providing versatile connection options for all your devices. The advanced audio system features quad speakers with dedicated woofers and tweeters, Dolby Atmos support, and automatic content-based sound optimization, creating an immersive audio experience without additional equipment. The intuitive smart TV platform provides access to thousands of apps and games, while the far-field microphones enable hands-free voice control from anywhere in the room. The AI Content Recommendation system learns your preferences over time, suggesting relevant content across streaming services. With built-in Chromecast, AirPlay 2 support, and seamless integration with Xiaomi smart home devices, this TV serves as both an entertainment hub and smart home control center. The ambient mode transforms the TV into a digital canvas when not in use, displaying artwork, photos, or useful information like weather and calendar appointments.', 30, 'assets/img/xiaomismarttva2025.webp', 30000, 8);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`cart_id`),
  ADD KEY `product` (`product_id`);

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`category_id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`order_id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cart`
--
ALTER TABLE `cart`
  MODIFY `cart_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `category_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `order_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=73;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `cart`
--
ALTER TABLE `cart`
  ADD CONSTRAINT `product` FOREIGN KEY (`product_id`) REFERENCES `products` (`product_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `category` (`category_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
